# Test your FastAPI endpoints

# Logins

POST http://127.0.0.1:8000/logins/add-login
Accept: application/json

###

GET http://127.0.0.1:8000/logins/email/username
Accept: application/json

###

PUT http://127.0.0.1:8000/logins/update-login
Accept: application/json

###

DELETE http://127.0.0.1:8000/logins/delete-login
Accept: application/json

###

GET http://127.0.0.1:8000/logins/email
Accept: application/json

###

# -----------------------------------------------------------------------------------------------

# Posts

POST http://127.0.0.1:8000/posts/add-post
Accept: application/json

###

GET http://127.0.0.1:8000/posts/email/date_time_utc
Accept: application/json

###

PUT http://127.0.0.1:8000/posts/update-post
Accept: application/json

###

DELETE http://127.0.0.1:8000/posts/delete-post
Accept: application/json

###

GET http://127.0.0.1:8000/posts
Accept: application/json

###

GET http://127.0.0.1:8000/scan-posts
Accept: application/json

###

# -----------------------------------------------------------------------------------------------

# Utilities

POST http://127.0.0.1:8000/utilities/upload-img
Accept: application/json

###

GET http://127.0.0.1:8000/utilities/object-key
Accept: application/json

###