# Test your FastAPI endpoints

# Logins

POST http://127.0.0.1:8000/logins/add-login
Accept: application/json

###

GET http://127.0.0.1:8000/logins/email/username
Accept: application/json

###

PUT http://127.0.0.1:8000/logins/update-login
Accept: application/json

###

DELETE http://127.0.0.1:8000/logins/delete-login
Accept: application/json

###

GET http://127.0.0.1:8000/logins/email
Accept: application/json

###

# -----------------------------------------------------------------------------------------------

# Posts

POST http://127.0.0.1:8000/posts/add-post
Accept: application/json

###

GET http://127.0.0.1:8000/posts/email/post-id
Accept: application/json

###

PUT http://127.0.0.1:8000/posts/update-post
Accept: application/json

###

DELETE http://127.0.0.1:8000/posts/delete-post
Accept: application/json

###

GET http://127.0.0.1:8000/posts/email
Accept: application/json

###

GET http://127.0.0.1:8000/posts
Accept: application/json

###
